name: crypto_coins_list # Название проекта
description: A new Flutter project. # Описание проекта
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  # Указание версии Flutter в проекте
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  # Зависимости приложения
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Работа с свг
  flutter_svg: ^2.0.5
  # Работа с запросами
  dio: ^5.2.1+1
  # Инъекции зависимостей
  get_it: ^7.6.0
  # Стейт-менеджер
  flutter_bloc: ^8.1.3
  # Библиотека сравнения
  equatable: ^2.0.5
  # Логгирование
  talker_flutter: ^3.1.7
  # Логгирование запросов в Dio
  talker_dio_logger: ^2.2.1
  # Логгирование в стейт-менеджере Bloc
  talker_bloc_logger: ^2.1.0
  # Интеграция Firebase
  firebase_core: ^2.15.0
  # Определяет аннотации, используемые json_serializable для создания кода для сериализации и десериализации JSON
  json_annotation: ^4.8.1

dev_dependencies:
  # Зависимости проекта для дев-режима
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Генерация DTO моделей в проекте для json
  json_serializable: ^6.6.0
  # Пакет для обработки других пакетов, занимающихся генерацией кода
  build_runner:

flutter:
  # Все дополнительные зависимости и конфиги

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
